### ISSUE TITLE
Daten in http://stat.integ.stadt-zuerich.ch/dataset/BRW-RAUM-ZEIT-EBA-HEA-HEO?view=Tabelle

### ISSUE THREAD

**Issue by MatthiasGuenter** [StatistikStadtZuerich/ld-data#119]
![grafik](https://user-images.githubusercontent.com/32902259/40576481-9f4ec014-60f7-11e8-861a-005c99bc6ecb.png)
http://stat.integ.stadt-zuerich.ch/dataset/BRW-RAUM-ZEIT-EBA-HEA-HEO?view=Tabelle

Die Analyse zeigt, dass die Daten so im Triple-Store sind.
Bsp: http://ld.integ.stadt-zuerich.ch/statistics/observation/BRW/R30000/ZXXXX2037/EBA2002/HEA8500/HEO0261 
ZXXXX2037R30000BRWEBA2002HEA8500HEO0261XXX0000XXX0000 mit Wert 0
ZXXXX2027R30000BRWEBA2001HEA8512HEO0261XXX0000XXX0000 mit Wert 53

BRW - Einbürgerungen
EBA2002 – Heirat der Eltern
EBA2001 - Einbürgerung
HEA8500 - Asien
HEA8512 - Irak

Massnahme: Mauro muss prüfen, ob diese Daten korrekt sind.

**Comment by ktk** [comment]
Data quality issue, closing here.
