### ISSUE TITLE
Glossarbeschreibung ist nicht vorhanden im Shape

### ISSUE THREAD

**Issue by MatthiasGuenter** [StatistikStadtZuerich/ld-data#134]
Im Shape fehlt die Beschreibung des Glossars für die Anzeige
Bsp: http://stat.integ.stadt-zuerich.ch/dataset/AVA-RAUM-ZEIT-SEX?format=turtle

![grafik](https://user-images.githubusercontent.com/32902259/42421922-dfa7575e-82dd-11e8-8c26-32a951c7588c.png)

**Comment by ktk** [comment]
Reference for #150 , need to see where to put that
