### ISSUE TITLE
ld-data bereitmachen für Freigabe des Repositories

### ISSUE THREAD

**Issue by MatthiasGuenter** [statistikstadtzuerich/ld-data#138]
- [x] Passwörter u.ä entfernen und commitete Passwörter auf Server ändern
- [x] Gibt es Bedenken gegen BSD 3 - Lizenz. Wenn nein, dann checken (Matthias R)
- [x] Lizenz einfügen

Freigabe selbst erst auf Statistiktage hin

**Comment by grandgrue** [comment]
Ist zwar schon auf closed - aber hier noch die Bestätigung: Beides ist ok für mich.
