### ISSUE TITLE
Metadaten für CKAN

### ISSUE THREAD

**Issue by ktk** [StatistikStadtZuerich/ld-data#149]
Auf Basis von CKAN Metadaten erstellen pro Cube/View, welche danach von CKAN abgefragt werden können.

@metaodi ich habe den Link nicht mehr offen, könntest Du ein Beispiel hier einfügen?

**Comment by metaodi** [comment]
Hier ist ein Beispiel eines CKAN Datasets in DCAT-AP: https://data.stadt-zuerich.ch/dataset/sid_dav_verkehrszaehlung_miv_od2031.ttl

Zu dieser reinen "Metadaten"-Sicht braucht es in den Distributions noch die Daten, die heute als CSV bereitgestellt werden.

**Comment by ktk** [comment]
Ich habe erst jetzt gemerkt, dass `.well-known/void` offiziell registiert wurde:

https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml

Sprich das wäre der Einstiegspunkt für den metadaten-slurper.

**Comment by ktk** [comment]
Todo:

- [ ] Struktur Catalog -> DataSet -> Distribution
- [ ] Media Type mitliefern in Distribution
- [ ] Service in DCAT für API Endpunkt
- [ ] Default CC0 Lizenz Property

**Comment by ktk** [comment]
Should be fine for the moment.
