### ISSUE TITLE
Zeit nach neuen Regeln umsetzen

### ISSUE THREAD

**Issue by MatthiasGuenter** [StatistikStadtZuerich/ld-data#82]
Adrian: ZEIT: Es gibt den ZXY-Eintrag. Bis zum ersten PJ, dann gab es Probleme. HDB.CSV. Bei den Perioden. PJ = Jahresperiode
Mauro ZPJ051930ZIP ist ein Code, nicht zu interpretieren. Bezugszeit: Periode, Datum: 1.1.1926-31.12.1930. Wert 19301231.
Adrian: Zeit wäre klassische Dimension, dann ginge das. String noch ausgeschrieben. Es gibt eine Timeontologie. Das Problem ist, TimeFilter sind dann sehr schwierig. Zusätzliches Join notwendig. Heute direkt als Datum der Observation angehängt.
Zeit Fall 1 ist auch ein Problem.
Mauro: Der Wechsel auf Monate oder Jahre ist wichtig. BEZUGSZEIT "Tag Monat Jahr", "Monat"= ist ein Monatbestand => jeden Monat.
TODO: BEZUGSZEIT wird auch modelliert. Tag, Monat, Jahr, Periode (können alles sein).
Adrian: API mässig: Wir tun den jetztigen Stand auf Prod. Integ auf Prod mergen. Dann haben wir den Stand mit dem klassischen Schnitt. Danach werde ich ZEIT zu klassischer Definition. Danach schaut Adrian mit Mauro wie der Zeitfilter aussieht für API.
Fall 2 Zeit gibt es (noch) nicht. Tendenziell eher als Kennzahhl
Fall 3 Zeit: Wird im Moment immer auf Stichtag gemacht. Mauro: Wir machen das über die Methode.
TODO: Erläuterung über Zeit.
Adrian: Es gibt Slices aus allen Kombinationen von Dimensionen. Muss es auch Slices mit unterschiedlichen Zeitdimension (Tag/Monat/Jahr)
Adrian: Bezugszeit direkt an Knoten angehängt.
TODO: Anschauen Mauro und Adrian

**Comment by ktk** [comment]
This is a proper dimension in the new data version. There are remaining questions that might pop up in using data in the future but closing this issue here.
